const listUsers = [
    {
        id: 1,
        fullname: 'John Doe',
        avatar: 'https://thuthuatnhanh.com/wp-content/uploads/2018/07/anh-dai-dien-dep.jpg',
        friendAmount: 143,
        mutualFriendAmount: 23,
        about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
        id: 2,
        fullname: 'Jane Smith',
        avatar: 'https://upanh123.com/wp-content/uploads/2020/12/anh-dai-dien-chat-cho-nu-1.jpg',
        friendAmount: 87,
        mutualFriendAmount: 12,
        about: 'Vivamus congue tincidunt metus, eu vehicula lorem blandit non.',
    },
    {
        id: 3,
        fullname: 'Bob Johnson',
        avatar: 'https://axinh.net/wp-content/uploads/2022/01/anh-avatar-cho-con-gai-cuc-dep-600x636.jpg',
        friendAmount: 283,
        mutualFriendAmount: 54,
        about: 'Suspendisse quis turpis nec felis malesuada auctor. Vivamus congue tincidunt metus. Pharetra auctor vel at elit.',
    },
    {
        id: 4,
        fullname: 'Emily Davis',
        avatar: 'https://taytou.com/wp-content/uploads/2022/05/anh-Avatar-dai-dien-DepAnh-avatar-chu-cun-nau-cuoi-dep-cute.jpg',
        friendAmount: 54,
        mutualFriendAmount: 7,
        about: 'Aliquam vitae eros id justo pharetra auctor vel at elit.',
    },
    {
        id: 5,
        fullname: 'James Smith',
        avatar: 'https://pgddakglong.edu.vn/wp-content/uploads/2023/04/tai-anh-anime-ve-lam-avatar7.jpg',
        friendAmount: 197,
        mutualFriendAmount: 35,
        about: 'Fusce nec ante vel nunc pharetra ullamcorper.',
    },
    {
        id: 6,
        fullname: 'Sarah Johnson',
        avatar: 'https://hinhnen4k.com/wp-content/uploads/2023/03/avatar-dep-cute-1.jpg',
        friendAmount: 109,
        mutualFriendAmount: 16,
        about: 'Pellentesque hendrerit tellus auctor nunc pharetra.',
    },
    {
        id: 7,
        fullname: 'Michael Williams',
        avatar: 'https://imgt.taimienphi.vn/cf/Images/np/2021/11/26/hinh-anh-avatar-dep-4.jpg',
        friendAmount: 72,
        mutualFriendAmount: 11,
        about: 'Ut non metus placerat, posuere metus vitae, posuere lorem.',
    },
    {
        id: 8,
        fullname: 'Emma Davis',
        avatar: 'https://wikithethao.com/wp-content/uploads/2018/05/Career-2.jpg',
        friendAmount: 312,
        mutualFriendAmount: 47,
        about: 'Integer commodo lacus in tincidunt placerat.',
    },
    {
        id: 9,
        fullname: 'Daniel Rodriguez',
        avatar: 'https://dmexco-lightsails-media.s3.eu-central-1.amazonaws.com/wp-content/uploads/2022/03/07092519/story_faszination-gamer_dmexco-scaled.jpg',
        friendAmount: 26,
        mutualFriendAmount: 3,
        about: 'Vestibulum sed quam a elit lacinia blandit.',
    },
    {
        id: 10,
        fullname: 'Ava Hernandez',
        avatar: 'https://cdn.vuanem.com/blog/wp-content/uploads/2023/02/cho-corgi.jpg',
        friendAmount: 163,
        mutualFriendAmount: 28,
        about: 'Donec euismod justo ac libero faucibus, sed tincidunt lacus pharetra.',
    },
];

export default listUsers;
